---

- name: "GlusterFS installation"
  hosts: default

  tasks:

    - name: "repository key installation"
      apt_key:
        url: https://download.gluster.org/pub/gluster/glusterfs/10/rsa.pub
        state: present

    - name: "repository configuration"
      apt_repository:
        repo: "deb [arch=amd64] https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{debian}}/amd64/apt {{debian}} main"
        state: present

    - name: "GlusterFS package"
      package:
        name: glusterfs-server={{glusterfs}}
        state: present

    - name: "server up and running"
      service:
        name: glusterd
        enabled: yes
        state: started
